// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing Supabase environment variables! Please check your .env file or deployment secrets (VITE_SUPABASE_URL, VITE_SUPABASE_PUBLISHABLE_KEY).");
}

// Initialization of the client.
// Even if URL is missing, we provide an empty string to avoid "undefined" errors, 
// though the client will still log an error if the URL is not a valid URL.
export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder'
);